services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: ${SQL_SA_PWD}
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis_cache:
    image: redis
    container_name: Redis-Cache
    ports:
      - "6379:6379"